---
title: "Reproducing Group-1's Findings"
author: "Arnab Dey, Michael Cheung"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  slidy_presentation:
    highlight: tango
    slide_level: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load-packages}
library(tidyverse)
library(stringr)
library(summarytools)
library(compareGroups)
library(cobalt)
library(survey)
library(WeightIt)
```

```{r load-dataset}
setwd("~/Documents/FMPH291 Reproducibility/Data")
df_master <- read.csv("group3_LATE_47215_3615162_DHS_shared-2.csv")
```

```{r filter cases for the study}
df_study <- df_master %>% 
  filter(v044 == 1) %>%     # Cases selected for IPV module
  filter(v502 == 1) %>%     # Drop cases that are not in union now
  filter(str_detect(vcal_1, "[123456789ACEFLMNSW]")) %>% # select only users of contraceptives
  filter(!str_detect(vcal_1, "[67]")) %>%  # Drop cases of sterilization
  filter(v701 != 8) %>%     # Drop those who do not know spousal edu
  filter(s116 != 8)      # Drop those who do not report caste

```


```{r Outcome Variable}

# those who discontinued contraceptive

df_study <- df_study %>% 
  mutate(disc = ifelse(str_detect(vcal_1, "[0PTB][123456789ACEFLMNSW]"), 1, 0))

```

```{r exposure variable}

df_study$any_ipv <- df_study %>% 
  mutate(n_d105a = ifelse(d105a == 1 | d105a == 2, 1, 0),
         n_d105b = ifelse(d105b == 1 | d105b == 2, 1, 0),
         n_d105c = ifelse(d105c == 1 | d105c == 2, 1, 0),
         n_d105d = ifelse(d105d == 1 | d105d == 2, 1, 0),
         n_d105e = ifelse(d105e == 1 | d105e == 2, 1, 0),
         n_d105f = ifelse(d105f == 1 | d105f == 2, 1, 0),
         n_d105h = ifelse(d105h == 1 | d105h == 2, 1, 0),
         n_d105i = ifelse(d105i == 1 | d105i == 2, 1, 0),
         n_d105j = ifelse(d105j == 1 | d105j == 2, 1, 0),
         n_d105k = ifelse(d105k == 1 | d105k == 2, 1, 0)) %>% 
  select(starts_with("n_")) %>% 
  mutate(total_ipv = rowSums(.)) %>% 
  mutate(any_ipv = ifelse(total_ipv > 0, 1, 0)) %>% 
  select(any_ipv) %>%
  as_vector() %>%
  as_factor()
  
```


```{r key-covariates}

# Age
df_study <- df_study %>% mutate(w_age = v012)

# Education
df_study <- df_study %>% 
  mutate(w_edu = ifelse(v106 > 1, 2, v106)) %>% 
  mutate(w_edu = factor(w_edu, levels = c(0,1,2), labels = c("No edu", "Primary", "Secondary or higher")))

# Spousal Education
df_study <- df_study %>% 
  mutate(m_edu = ifelse(v701 > 1, 2, v701)) %>% 
  mutate(m_edu = factor(m_edu, levels = c(0,1,2), labels = c("No edu", "Primary", "Secondary or higher")))

# Wealth
df_study <- df_study %>% mutate(wealth = v190) %>% 
  mutate(wealth = factor(wealth, levels = c(1:5), labels = c("Poorest", "Poorer", 
                                                             "Middle", "Richer", "Richest")))


# Place of residence
df_study <- df_study %>% mutate(residence = v025) %>% 
  mutate(residence = factor(residence, levels = c(1,2), labels = c("Urban", "Rural")))


# Num boys
df_study <- df_study %>% mutate(tot_boys = v202 + v204) %>% 
  mutate(boys_cat = ifelse(tot_boys > 1, 2, tot_boys)) %>% 
  mutate(boys_cat = factor(boys_cat, levels = c(0:2), labels = c("Zero", "One", "Two+")))

# Num daughters
df_study <- df_study %>% mutate(tot_girls = v203 + v205) %>% 
  mutate(girls_cat = ifelse(tot_girls > 1, 2, tot_girls)) %>% 
  mutate(girls_cat = factor(girls_cat, levels = c(0:2), labels = c("Zero", "One", "Two+")))

# Social Caste

df_study <- df_study %>% mutate(caste = s116) %>% 
  mutate(caste = factor(caste, levels = c(1:4), labels = c("SC", "ST", "OBC", "GEN")))


# Religion
df_study <- df_study %>% mutate(religion = ifelse(v130 > 2, 3, v130)) %>% 
  mutate(religion = factor(religion, levels = c(1:3), labels = c("Hindu", "Muslim", "Other")))

```

```{r survey weights, psu, strata}
#weights
df_study <- df_study %>%
  mutate(weights = d005/(10^6)) %>%
  dplyr::rename(psu = v021,
                strata = v022,
                area_unit = v004)
```

```{r variable selection}
outcome <- "disc"
exposure <- "any_ipv"
covariates <- c("w_age", "w_edu", "m_edu", "wealth", "residence", "boys_cat", "girls_cat", "caste", "religion")

df_1 <- select(df_study, all_of(c(outcome, exposure, covariates)), "weights", "psu", "strata", "area_unit")
```

```{r Table 1, results='hide'}
options(survey.lonely.psu = "average")
#survey design
design_wt <- svydesign(ids = df_1$psu,
                       strata = df_1$strata,
                       weights = df_1$weights,
                       data = df_1)

#table 1 structure
table1_names <- c(all_of(c(exposure, covariates)))


tab1.1.cg <- compareGroups(~. - disc, data = select(df_1, all_of(c(table1_names, outcome))))
tab1.1 <- createTable(tab1.1.cg, show.n = F)
tab1.2 <- update(tab1.1, x = update(tab1.1.cg, disc ~ .), show.p.overall = F)
# table1 <- cbind("Total sample" = tab1.1, "Discontinued method in past 12 months" = tab1.2)

#Export to csv; don't uncomment when knitting file
# export2csv(tab1.1, file = "phase2_tab1_1.csv")
# export2csv(tab1.2, file = "phase2_tab1_2.csv")
# 
# tab1.1.df <- read.csv("phase2_tab1_1.csv")
# tab1.2.df <- read.csv("phase2_tab1_2.csv")
# 
# table1 <- cbind(tab1.1.df, tab1.2.df[,2:3])
# names(table1) <- c("Covariates", "Total sample", "Did not discontinue contraceptives", "Discontinued contraceptives")
# 
# write_csv(table1, "table1.csv")

##edit weighted %s and weighted mean/SD for w_age - manually entered in table1.csv for now
#outcome %s
round(prop.table(svytable(~disc, design_wt, round = T)) * 100, 1)

#any_ipv
#not grouped
round(prop.table(svytable(~any_ipv, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~any_ipv + disc, design_wt, round = T), 2) * 100, 1)

#w_age
#not grouped
round(svymean(~w_age, design_wt)[1], 1)
round(sqrt(svyvar(~w_age, design_wt)[1]), 2)
#grouped
round(svyby(~w_age, ~disc, design_wt, svymean)[,-3], 1)
round(sqrt(svyby(~w_age, ~disc, design_wt, svyvar)[,-3]), 2)

#w_edu
#not grouped
round(prop.table(svytable(~w_edu, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~w_edu + disc, design_wt, round = T), 2) * 100, 1)

#m_edu
#not grouped
round(prop.table(svytable(~m_edu, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~m_edu + disc, design_wt, round = T), 2) * 100, 1)

#wealth
#not grouped
round(prop.table(svytable(~wealth, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~wealth + disc, design_wt, round = T), 2) * 100, 1)

#residence
#not grouped
round(prop.table(svytable(~residence, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~residence + disc, design_wt, round = T), 2) * 100, 1)

#boys_cat
#not grouped
round(prop.table(svytable(~boys_cat, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~boys_cat + disc, design_wt, round = T), 2) * 100, 1)

#girls_cat
#not grouped
round(prop.table(svytable(~girls_cat, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~girls_cat + disc, design_wt, round = T), 2) * 100, 1)

#caste
#not grouped
round(prop.table(svytable(~caste, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~caste + disc, design_wt, round = T), 2) * 100, 1)

#religion
#not grouped
round(prop.table(svytable(~religion, design_wt, round = T)) * 100, 1)
#grouped
round(prop.table(svytable(~religion + disc, design_wt, round = T), 2) * 100, 1)
```

## Table 1
```{r, results='markup'}
table1.final <- read.csv("table1.csv")
table1.final
```


```{r Table 2, results='hide'}
#table 1 structure
tab2.cg <- compareGroups(any_ipv ~., data = select(df_1, all_of(c(covariates, exposure))))
tab2 <- createTable(tab2.cg, show.n = F)

#Export to csv; don't uncomment when knitting file
# export2csv(tab2, file = "table2.csv", header.labels = c(p.overall = "p-value"))

##edit weighted %s and weighted mean/SD for w_age - manually entered in table1.csv for now
#exposure %s
round(prop.table(svytable(~any_ipv, design_wt, round = T)) * 100, 1)

#w_age
round(svyby(~w_age, ~as.integer(any_ipv), design_wt, svymean)[,-3], 1)
round(sqrt(svyby(~w_age, ~as.integer(any_ipv), design_wt, svyvar)[,-3]), 2)
#t-test
round(svyttest(w_age ~ any_ipv, design_wt)$p.value, 3)

#w_edu
round(prop.table(svytable(~w_edu + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~w_edu + any_ipv, design_wt)$p.value

#m_edu
round(prop.table(svytable(~m_edu + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~m_edu + any_ipv, design_wt)$p.value

#wealth
round(prop.table(svytable(~wealth + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~wealth + any_ipv, design_wt)$p.value

#residence
round(prop.table(svytable(~residence + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~residence + any_ipv, design_wt)$p.value

#boys_cat
round(prop.table(svytable(~boys_cat + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~boys_cat + any_ipv, design_wt)$p.value

#girls_cat
round(prop.table(svytable(~girls_cat + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~girls_cat + any_ipv, design_wt)$p.value

#caste
round(prop.table(svytable(~caste + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~caste + any_ipv, design_wt)$p.value

#religion
round(prop.table(svytable(~religion + any_ipv, design_wt, round = T), 2) * 100, 1)
#pearson chi-square test
svychisq(~religion + any_ipv, design_wt)$p.value
```

## Table 2
```{r, results='markup'}
table2.final <- read.csv("table2.csv")
table2.final
```

```{r Table 3}
#propensity score
PropScore <- predict(glm(any_ipv ~ w_age + w_edu + m_edu + wealth + residence + boys_cat + girls_cat + caste + religion,
                         family = binomial,
                         data = df_1),
                     type = "response")

#proportion exposed
prop_exposed <- mean(as.integer(df_1$any_ipv) - 1)

#create standardized weights 
df_1 <- df_1 %>%
  mutate(PS = PropScore,
         ps.weights = ifelse(any_ipv == 1, 
                          prop_exposed/PS, 
                          (1-prop_exposed)/(1-PS)))

#truncate weights at 5th and 95th percentiles
cutoff_5th <- quantile(df_1$ps.weights, probs = .05)
cutoff_95th <- quantile(df_1$ps.weights, probs = .95)

df_1 <- df_1 %>%
  mutate(trunc_weights = case_when(ps.weights < cutoff_5th ~ cutoff_5th,
                                   ps.weights > cutoff_95th ~ cutoff_95th,
                                   ps.weights >= cutoff_5th && ps.weights <= cutoff_95th ~ ps.weights))

#Table 3 balance tests 
table3.1 <- bal.tab(any_ipv ~ w_age + w_edu + m_edu + wealth + residence + boys_cat + girls_cat + caste + religion, 
                    data = df_1)
table3.2 <- bal.tab(any_ipv ~ w_age + w_edu + m_edu + wealth + residence + boys_cat + girls_cat + caste + religion,
                    data = df_1, 
                    weights = "trunc_weights")

tab3.1 <- as.data.frame(table3.1$Balance)
tab3.2 <- as.data.frame(table3.2$Balance)

table3.final <- cbind(tab3.1,tab3.2)
table3.final <- round(table3.final[,c(2,6)], 3)

write.csv(table3.final, "table3.csv")
```

## Table 3
```{r, results='markup'}
table3.final
```
